[package]
name = "csvcat"
version = "0.1.0"
edition = "2021"

[lib]
name = "csvcat"
path = "src/lib.rs"

[[bin]]
name = "csvcat"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
